name: Playwright Tests
on:
  push:
    branches: [ main, master ]
jobs:
   playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install playwright browsers
      run: npx playwright install --with-deps
    - name: Run tests
      run: npx playwright test


 